baseURL = 'https://example.org/'
languageCode = 'ja-JP'
title = 'dzfl.jp'

defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = false
# 日本語のようなスペース区切りのない言語で文字数を正しくカウントする
hasCJKLanguage = true
# 自動要約の長さを調整（文字数に近い感覚になります）
summaryLength = 20

disableKinds = ['taxonomy', 'term']


theme = "mytheme"

contentDir = "../source"
staticDir  = ["../.gen/static", "themes/mytheme/static"]
publishDir = "../.gen/public"


[params]
  author = "dzfl"
  description = "個人ブログ"
  social_bluesky = "https://bsky.app/profile/dzfl.bsky.social"
  social_x = "https://x.com/dzfl"
  social_youtube = "https://www.youtube.com/@dzfl"


[pagination]
  disableAliases = true
  pagerSize = 5
  path = ''


[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog/'
    weight = 20

  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 30

#  [[menus.footer]]
#    name = ''
#    pageRef = '/'
#    weight = 10




[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'

[markup]
  [markup.highlight]
    # インラインスタイルを使用（true）かCSSクラスを使用（false）
    noClasses = false
    
    # コードフェンスを有効化
    codeFences = true
    
    # 行番号は不要
    lineNos = false
    
    # ベーススタイル（CSSで上書き可能）
    style = "github"

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true

